### PR TITLE
Add handlers to validate methode and introduce format_checkers

### PR DESCRIPTION
**Pull request by ystreibel**
Hello,

We would like to contribute in this project by adding the format_checkers feature that consists to allow custom format to be check during the `compile` method execution. 
The format_checkers is optional and only available for `compile`.

A fellow, @gpakosz, already contact you about this.

Thanks

### CODE REVIEW

**Comment by gpakosz** [comment]
Hello @horejsek 👋

As discussed by email, we thought it makes sense to augment `validate()` and `compile()` with a `format_checkers` dict that maps a format name to a callable. The current implementation assumes nothing of the callables:
  - they can be stateful
  - they can raise anything (which will be propagated with Python 3 exception chaining)

This is a feature we need to move from `python-jsonschema` which is too slow for our current workload.

**Comment by horejsek** [comment]
Thank you for pull request.

I would like to see tests for that. Other improvement I think could be to do custom formats first to be able to override formats from the JSON spec. Could we also call it simply `formats` and have there callbacks or regular expressions? If the check can be only regular expression, then it can be much faster than callbacks.

**Comment by gpakosz** [comment]
Hello @horejsek,

The current implementation indeed doesn't replace the existing format checking that's regex based. Maybe we should just do that instead of running after the default ones.

Agreed with naming the dict `formats` and make it either a callback or a regular expression. What types do you think should be supported as values?
  - `str`, `re.Pattern`, `function`?
  - or just `re.Pattern` and `function`?

**Comment by horejsek** [comment]
Because often regular expression is written as `r"..."`, I would allow `str` being interpreted as regular expression as well.

**Comment by ystreibel** [comment]
Hello, I took your requests into consideration. 

Now, I would need more information about testing! I would like to know where could I add my tests.
It seems to be in template_test function in utils.py and add it in the compile but if I do that I couldn't test all the formats types (str, re.Pattern, function) but just one.

Thank you.

**Comment by ystreibel** [comment]
Hello @horejsek 👋,

Did you see my previous comment? We really need to know how to improve the test suits to finalize this PR.

Thank you

**Comment by horejsek** [comment]
Sorry, I have a lot of things going on last two month and couldn't pay attention to this issue.

`utils.py` in json_schema folder is meant for test suits from JSON Schema. Do not use this one for this. Write your own test in tests folder. Because you are changing how format feature is working, there is file `tests/test_format.py` for that. You can see usage of `asserter` which is defined in `conftest.py`, see: https://github.com/horejsek/python-fastjsonschema/blob/master/tests/conftest.py#L17 You can add parameter (not required) which will also configure format checkers and then you can write tests similar to ones already in `test_format.py`.

**Comment by ystreibel** [comment]
Hi @horejsek ,

I added some tests as you explained me. You could finally check the PR.
Thank you for this help.

**Comment by horejsek** [comment]
Those tests are specific to your custom formats, this library needs tests which cover the functionality itself. I will do it. Also, re.Pattern is there since Python 3.7 and I officially still support 3.3. That's maybe old, but at least 3.5 is needed. I will also fix that.

**Comment by horejsek** [comment]
BTW your tests actually do not work at all...

**Pull request merged**
