### PR TITLE
Fix unexpected caching (issue #129)

### LINKED ISSUE #129: Unexpected caching when swapping `handlers` on `compile` function
Hello, recently I noticed that I cannot use the `compile` function twice if there is a change in the schemas...
Even when I change the handlers, the schemas are getting globally cached somehow...

The following example illustrates the problem:

```python
>>> from fastjsonschema import compile
>>> repo1 = {
...     "sch://schema1": {"type": "array"}
... }
>>> repo2 = {
...     "sch://schema1": {"type": "string"}
... }
>>> validator1 = compile({"$ref": "sch://schema1"}, handlers={"sch": repo1.__getitem__})
>>> assert validator1([1, 2, 3]) == [1, 2, 3]
>>> validator1([1, 2, 3])
[1, 2, 3]

>>> validator2 = compile({"$ref": "sch://schema1"}, handlers={"sch": repo2.__getitem__})
>>> validator2("hello world")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in validate
  File "<string>", line 9, in validate_sch___schema1
fastjsonschema.exceptions.JsonSchemaValueException: data must be array

data must be array
>>>
```

I think this problem is happening because of the definition of the `RefResolver`:
```python
def __init__(self, base_uri, schema, store={}, cache=True, handlers={}):
    #                                      ^--- This is a mutable default (and I believe the culprit)
    ...
```
(probably related to the usage of a mutable value as default argument, ref: https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/)

### PR DESCRIPTION
**Pull request by abravalheri**
This PR is an attempt to fix #129.

The approach adopted here was to replace all the empty dictionaries used as mutable default arguments with `None` and use the handy `self.value = value or {}` expression to make sure we have an empty default dictionary...

### CODE REVIEW

**Comment by horejsek** [comment]
Thanks for finding the issue and preparing PR! Did you find the root issue? Because I would like to keep {} in the definition if possible, I like it like that so the doc is nicely generated and clear what type it expects.

**Comment by abravalheri** [comment]
Hi @horejsek thank you very much for the review.

I am afraid that function calls that do not specify all the arguments but instead rely on a default mutable argument are the root cause of the problem  😅

If you want to keep the empty dict in the function definition,  then the only way around is to always make sure all the calls to the function pass explicitly the handlers and formats arguments.

At that point it would be easier to make them mandatory arguments without a default value, right? If documentation is the problem, there could be a type annotation to cover for the lack of a default value...

There is another, not elegant workaround, that would be checking if the argumebt is empty and assigning a brand new dict to it...

**Comment by horejsek** [comment]
The mutable objects can be issue for sure. But this seems like something a bit different. What I meant is that probably there is only one place which is problematic, and not all the others need the change. I will take look into it later. If my feeling is correct, then I would prefer to keep interface as is and fix differently. If not, I will accept your solution.

**Comment by abravalheri** [comment]
Thanks @horejsek . Is it OK if I investigate this one better next week? I don't have access to a computer right now 😅

**Comment by horejsek** [comment]
Sure, no problem. I thought I will take a look. But if you want to deep more and will be faster than me (that might be true), feel free to do so. :)

**Comment by abravalheri** [comment]
Hi @horejsek, I hunted down the specific function calls that are responsible for this error and changed the PR to fix only them.

Please notice that the argument `store` for `RefResolver` should be seen as "mandatory" (instead of relying on its default values), otherwise the caching problems may occur.

Please notice that this approach does not prevent future errors to happen in other places, the code using empty dicts as default arguments is still error prone (although very handy for documentation purposes as you mentioned before).

**Pull request merged**
